apiVersion: v1
kind: Pod
metadata:
  name: go-pod
  labels:
    env: demo
    owner: heshihao
    app: api-gateway

spec:
  containers:
  - image: heshihao0720/HPCP-P/API-Gateway-Server:latest
    name: go
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80        # 服务对外端口
    targetPort: 8080 # 容器内端口
  type: ClusterIP