name: Deploy Test
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"
      - name: run deployment with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_ADDRESS }}
          username: ${{ vars.SERVER_USER  }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{vars.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t heshihao0720/HPCP-P/API-Gateway-Server:${{ steps.version.outputs.VERSION }} .
            docker push heshihao0720/HPCP-P/API-Gateway-Server:${{ steps.version.outputs.VERSION }}
            chmod +x auto_deploy.sh
            VERSION=${{ steps.version.outputs.VERSION }} sh auto_deploy.sh